# Generated by Django 6.0 on 2026-01-22 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
