# Generated by Django 6.0 on 2026-02-02 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_passwordresetotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managed_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
