# Generated by Django 6.0 on 2026-02-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_managed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
