# Generated by Django 6.0 on 2026-02-03 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_organization_name_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="destination",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="management",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="number_plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="bus_photos/"),
        ),
    ]
