# Generated by Django 6.0 on 2026-02-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_bus_destination_bus_management_bus_number_plate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="route_name",
        ),
    ]
