# Generated by Django 6.0 on 2026-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_bus_route_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="bus_number",
            field=models.CharField(max_length=20),
        ),
    ]
