# Generated by Django 6.0 on 2026-02-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_boardinglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardinglog",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardinglog",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
