# Generated by Django 6.0 on 2026-02-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_bus_last_update_bus_latitude_bus_longitude_trip"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="boardinglog",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="boardinglog",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boarding_logs",
                to="accounts.trip",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="evening_trip_start_time",
            field=models.TimeField(default="12:00:00"),
        ),
        migrations.AddField(
            model_name="bus",
            name="morning_trip_end_time",
            field=models.TimeField(default="12:00:00"),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_type",
            field=models.CharField(
                choices=[("morning", "Morning"), ("evening", "Evening")],
                default="morning",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boardinglog",
            unique_together={("student", "trip")},
        ),
    ]
