# Generated by Django 6.0 on 2026-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0015_alter_boardinglog_unique_together_boardinglog_trip_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="evening_departure_time",
            field=models.TimeField(
                default="16:00:00",
                help_text="Time from which buses depart from college",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="morning_arrival_time",
            field=models.TimeField(
                default="09:00:00",
                help_text="Time by which buses should arrive at college",
            ),
        ),
    ]
