# Generated by Django 6.0 on 2026-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_user_evening_departure_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="push_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
